version: '3.8'

services:
  consumer:
    build:
      context: ..
      dockerfile: Consumer/Dockerfile
    image: your-dockerhub-username/consumer-app:latest
    ports:
      - "8082:8082" # Maps host port 8082 to container port 8082
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"   # Messaging port changed to avoid conflict with Producer's RabbitMQ
      - "15673:15672" # Management UI port changed
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
